### ISSUE TITLE
Yo, I need somethin' somethin'

### ISSUE THREAD

**Issue by marangachweya** [codersreign/student-registration-form#1]
**YO I NEED SOMETHIN' SOMETHIN'**
Hey @codersreign I would like to request something.
If I fix up your School Website Template. Can I get
your consent to re-upload it onto GitHub as my own
with tweaks? Such as linking em'!
Ok Thanks, 
An Informal & Formal Email from Alvin Chweya.
Kind Regards
Alvin .M. Chweya (@marangachweya)

**Comment by marangachweya** [comment]
Thanks, Hopefully I get a response

**Comment by codersreign** [comment]
Ye yeah you can do this. No issue. Feel free to put it on your GitHub. You
have my consent :)

Thank You

All the Best to your Coding Journey!

**Comment by marangachweya** [comment]
I'm so sorry I haven't seen your comment, But I thank you! I'll make sure to subscribe!

**Comment by codersreign** [comment]
Thanks Buddy ! :)
